package dev.openallay.build;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import javax.tools.*;
public final class CanonicalTextBlockPortFixture {
    private static final String SOURCE="public class TextFlow { public static void main(String[]args){String value=\"\"\"\n    first\\s\n      quote=\\\" and slash=\\\\\n    joined\\\n    line\n    🐝\n    \"\"\"; byte[]bytes=value.getBytes(java.nio.charset.StandardCharsets.UTF_8);StringBuilder out=new StringBuilder();for(byte b:bytes)out.append(String.format(\"%02x\",b&255));System.out.println(out);}}";
    private static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
    private static String run(String java,List<String>args)throws Exception{List<String>command=new ArrayList<>();command.add(java);command.addAll(args);Process child=new ProcessBuilder(command).redirectErrorStream(true).start();String text=new String(child.getInputStream().readAllBytes(),StandardCharsets.UTF_8);check(child.waitFor()==0,"Actualcompiler/runtime failed "+command+" "+text);return text.replace("\r\n","\n");}
    private static void compile(Path source,Path classes,String release)throws Exception{Files.createDirectory(classes);JavaCompiler compiler=ToolProvider.getSystemJavaCompiler();DiagnosticCollector<JavaFileObject>diagnostics=new DiagnosticCollector<>();try(StandardJavaFileManager manager=compiler.getStandardFileManager(diagnostics,Locale.ROOT,StandardCharsets.UTF_8)){check(compiler.getTask(null,manager,diagnostics,List.of("--release",release,"-proc:none","-encoding","UTF-8","-d",classes.toString()),null,manager.getJavaFileObjects(source.toFile())).call(),"Genuinecompiler failed "+diagnostics.getDiagnostics());}}
    public static void main(String[]args)throws Exception{if(args.length!=4)throw new IllegalArgumentException("freshRoot modernJava trueJavac8 trueJava8");Path root=Paths.get(args[0]);Files.createDirectory(root);check(run(args[2],List.of("-version")).startsWith("javac 1.8."),"Truejavac8");check(run(args[3],List.of("-version")).contains("version \"1.8."),"Truejava8");Path original=root.resolve("original");Files.createDirectory(original);Path before=original.resolve("TextFlow.java");Files.writeString(before,SOURCE);Path selected=root.resolve("selected.txt");Files.writeString(selected,"TextFlow.java\n");Path converted=root.resolve("converted");CanonicalTextBlockPort.main(new String[]{original.toString(),selected.toString(),converted.toString()});check(Files.readString(converted.resolve("literal-counts.tsv")).equals("TextFlow.java\t1\n"),"Oneactualtextblock");Path after=converted.resolve("post/TextFlow.java");Path modern=root.resolve("modern"),release8=root.resolve("release8"),true8=root.resolve("true8");compile(before,modern,"17");compile(after,release8,"8");Files.createDirectory(true8);run(args[2],List.of("-source","8","-target","8","-encoding","UTF-8","-d",true8.toString(),after.toString()));String expected=run(args[1],List.of("-cp",modern.toString(),"TextFlow"));check(run(args[3],List.of("-cp",release8.toString(),"TextFlow")).equals(expected),"Exactpublicliteralvalue release8");check(run(args[3],List.of("-cp",true8.toString(),"TextFlow")).equals(expected),"Exactpublicliteralvalue truejavac8");System.out.println("PASS textblock original17=release8=truejavac8 actualUTF8value indentation/spaceEscape/lineContinuation/quote/backslash/supplementary preserved");}
}
