package dev.openallay.build;
import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import javax.tools.*;
public final class CanonicalWhilePatternFixture {
 private static final String SOURCE="""
 import java.util.*;
 public class WhileFlow {
  static int calls;static Object[] input={"a","b",Integer.valueOf(3),"ignored"};static int index;
  static Object next(){calls++;return input[index++];}
  public static void main(String[]args){StringBuilder out=new StringBuilder();while(next() instanceof String text && !text.isEmpty()){out.append(text);if(text.equals("a"))continue;if(text.equals("b"))break;}out.append(":"+calls);index=0;calls=0;while(next() instanceof String text && !text.isEmpty()){out.append(text);}out.append(":"+calls);calls=0;while(false && next() instanceof String lazy){out.append(lazy);}out.append(":"+calls);System.out.println(out);}
 }
 """;
 private static void check(boolean v,String m){if(!v)throw new AssertionError(m);}private static String run(String bin,List<String>args)throws Exception{List<String>cmd=new ArrayList<>();cmd.add(bin);cmd.addAll(args);Process p=new ProcessBuilder(cmd).redirectErrorStream(true).start();String out=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);check(p.waitFor()==0,cmd+" "+out);return out.replace("\r\n","\n");}
 private static void compile(Path source,Path classes,String release)throws Exception{Files.createDirectory(classes);JavaCompiler c=ToolProvider.getSystemJavaCompiler();DiagnosticCollector<JavaFileObject>d=new DiagnosticCollector<>();try(StandardJavaFileManager m=c.getStandardFileManager(d,Locale.ROOT,StandardCharsets.UTF_8)){check(c.getTask(null,m,d,List.of("--release",release,"-proc:none","-d",classes.toString()),null,m.getJavaFileObjects(source.toFile())).call(),d.getDiagnostics().toString());}}
 public static void main(String[]args)throws Exception {if(args.length!=4)throw new IllegalArgumentException("freshroot modernJava truejavac8 truejava8");Path root=Paths.get(args[0]);Files.createDirectory(root);Path original=root.resolve("original");Files.createDirectory(original);Path source=original.resolve("WhileFlow.java");Files.writeString(source,SOURCE);Path selected=root.resolve("selected.txt");Files.writeString(selected,"WhileFlow.java\n");Path output=root.resolve("converted");CanonicalPatternPort.main(new String[]{original.toString(),"",selected.toString(),output.toString()});check(Files.readString(output.resolve("owner-status.tsv")).equals("WhileFlow.java\tSUPPORTED\t3\t0\n"),"Exactwhileownerproof");Path modern=root.resolve("modern"),release8=root.resolve("release8"),actual8=root.resolve("actual8");compile(source,modern,"17");compile(output.resolve("post/WhileFlow.java"),release8,"8");Files.createDirectory(actual8);run(args[2],List.of("-source","8","-target","8","-d",actual8.toString(),output.resolve("post/WhileFlow.java").toString()));String expected="ab:2ab:3:0\n";check(run(args[1],List.of("-cp",modern.toString(),"WhileFlow")).equals(expected),"Originalwhileevaluation");check(run(args[3],List.of("-cp",release8.toString(),"WhileFlow")).equals(expected),"Release8");check(run(args[3],List.of("-cp",actual8.toString(),"WhileFlow")).equals(expected),"True8");Path unsupported=root.resolve("unsupported");Files.createDirectory(unsupported);Files.writeString(unsupported.resolve("ForFlow.java"),"class ForFlow { boolean run(Object value){for(;value instanceof String bound;){return bound.isEmpty();}return false;} }");Path badSelection=root.resolve("bad-selection.txt");Files.writeString(badSelection,"ForFlow.java\n");Path bad=root.resolve("bad");CanonicalPatternPort.main(new String[]{unsupported.toString(),"",badSelection.toString(),bad.toString()});check(Files.readString(bad.resolve("owner-status.tsv")).contains("\tREJECTED\t1\t"),"FORremainsunsupported");check(!Files.exists(bad.resolve("post/ForFlow.java")),"NopartialFORoutput");System.out.println("PASS exactperiterationholder whilepattern/lazy/break/continue"); }
}
