package dev.openallay.build;
import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import javax.tools.*;
/** Captured methodread policy uses actualdeclaredwildcards/memberreturnbounds, not a blanket Object guess. */
public final class CanonicalCapturedCallPatternFixture {
 private static final String SOURCE="""
 import java.util.*;
 public class CapturedCallFlow {
  static int calls;
  interface Tool<A,B>{}static class Skill implements Tool<String,Integer>{}
  static class Registered {Tool<?,?> tool(){calls++;return new Skill();}}
  static class Success<T>{final T value;Success(T value){this.value=value;}T value(){calls++;return value;}}
  static String run(Success<?> success){return success.value() instanceof String text?text.toUpperCase(Locale.ROOT):"other";}
  public static void main(String[]args){StringBuilder out=new StringBuilder();Registered registered=new Registered();if(registered.tool() instanceof Skill skill)out.append(skill.getClass().getSimpleName());out.append(run(new Success<String>("text"))).append(run(new Success<Integer>(1))).append(run(new Success<Object>(null)));boolean skip=true;if(!skip && registered.tool() instanceof Skill lazy)out.append("bad");List<Registered> rows=Arrays.asList(registered);out.append(rows.stream().map(r->r.tool() instanceof Skill skill?"lambda":"bad").collect(java.util.stream.Collectors.joining()));System.out.println(out+":"+calls);}
 }
 """;
 private static void check(boolean b,String m){if(!b)throw new AssertionError(m);}private static String run(String binary,List<String>args)throws Exception{List<String>cmd=new ArrayList<>();cmd.add(binary);cmd.addAll(args);Process p=new ProcessBuilder(cmd).redirectErrorStream(true).start();String text=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);check(p.waitFor()==0,cmd+" "+text);return text.replace("\r\n","\n");}
 private static void compile(Path source,Path classes,String release)throws Exception{Files.createDirectory(classes);JavaCompiler c=ToolProvider.getSystemJavaCompiler();DiagnosticCollector<JavaFileObject>d=new DiagnosticCollector<>();try(StandardJavaFileManager m=c.getStandardFileManager(d,Locale.ROOT,StandardCharsets.UTF_8)){check(c.getTask(null,m,d,List.of("--release",release,"-proc:none","-d",classes.toString()),null,m.getJavaFileObjects(source.toFile())).call(),d.getDiagnostics().toString());}}
 public static void main(String[]args)throws Exception{if(args.length!=4)throw new IllegalArgumentException("freshroot modernJava truejavac8 truejava8");Path root=Paths.get(args[0]);Files.createDirectory(root);Path original=root.resolve("original");Files.createDirectory(original);Path source=original.resolve("CapturedCallFlow.java");Files.writeString(source,SOURCE);Path selected=root.resolve("selected.txt");Files.writeString(selected,"CapturedCallFlow.java\n");Path converted=root.resolve("converted");CanonicalPatternPort.main(new String[]{original.toString(),"",selected.toString(),converted.toString()});check(Files.readString(converted.resolve("owner-status.tsv")).equals("CapturedCallFlow.java\tSUPPORTED\t4\t0\n"),"Exact captured callcount fixture supported");String post=Files.readString(converted.resolve("post/CapturedCallFlow.java"));check(post.contains("Tool<?, ?> value")||post.contains("Tool<?,?> value")||post.contains("CapturedCallFlow.Tool<?, ?> value"),"DeclaredwildcardToolreturnnoterased");Path modern=root.resolve("modern"),release8=root.resolve("release8"),actual8=root.resolve("actual8");compile(source,modern,"17");compile(converted.resolve("post/CapturedCallFlow.java"),release8,"8");Files.createDirectory(actual8);run(args[2],List.of("-source","8","-target","8","-d",actual8.toString(),converted.resolve("post/CapturedCallFlow.java").toString()));String expected="SkillTEXTotherotherlambda:5\n";check(run(args[1],List.of("-cp",modern.toString(),"CapturedCallFlow")).equals(expected),"Originalcallorder");check(run(args[3],List.of("-cp",release8.toString(),"CapturedCallFlow")).equals(expected),"Release8");check(run(args[3],List.of("-cp",actual8.toString(),"CapturedCallFlow")).equals(expected),"True8");System.out.println("PASS exactdeclaredcapturedmethod wildcard/memberreturn and lazy evaluation oracle");}
}
