package dev.openallay.build;
import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import javax.tools.*;
/** Real peer-binding reads inside later pattern operands: composition not generic type erasure. */
public final class CanonicalPatternCompositionFixture {
 private static final String SOURCE="""
 import java.util.*;
 public class CompositionFlow {
  static int reads;static int calls;
  static final class Success<T>{final T value;Success(T value){this.value=value;}T value(){reads++;return value;}}
  interface Visual{String image();}static final class Picture implements Visual{public String image(){return "image";}}
  static Object source(Object value){calls++;return value;}
  static String render(Object result){return result instanceof Success<?> succeeded && succeeded.value() instanceof Visual visual ? visual.image() : "none";}
  static String blocks(Object result){if(source(result) instanceof Success<?> success){if(success.value() instanceof Visual visual){java.util.function.Supplier<String> lambda=()->visual.image();return lambda.get();}}return "none";}
  public static void main(String[]args){StringBuilder out=new StringBuilder();out.append(render(new Success<Picture>(new Picture())));out.append(render(new Success<String>("x")));out.append(render(Integer.valueOf(1)));out.append(blocks(new Success<Picture>(new Picture())));List<Object> results=Arrays.asList(new Success<Picture>(new Picture()),Integer.valueOf(1));out.append(results.stream().map(result->result instanceof Success<?> success && success.value() instanceof Visual visual?visual.image():"none").collect(java.util.stream.Collectors.joining()));System.out.println(out+":"+reads+":"+calls);}
 }
 """;
 private static void check(boolean b,String m){if(!b)throw new AssertionError(m);}private static String run(String binary,List<String>args)throws Exception{List<String>cmd=new ArrayList<>();cmd.add(binary);cmd.addAll(args);Process p=new ProcessBuilder(cmd).redirectErrorStream(true).start();String text=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);check(p.waitFor()==0,cmd+" "+text);return text.replace("\r\n","\n");}
 private static void compile(Path source,Path classes,String release)throws Exception{Files.createDirectory(classes);JavaCompiler c=ToolProvider.getSystemJavaCompiler();DiagnosticCollector<JavaFileObject>d=new DiagnosticCollector<>();try(StandardJavaFileManager m=c.getStandardFileManager(d,Locale.ROOT,StandardCharsets.UTF_8)){check(c.getTask(null,m,d,List.of("--release",release,"-proc:none","-d",classes.toString()),null,m.getJavaFileObjects(source.toFile())).call(),d.getDiagnostics().toString());}}
 public static void main(String[]args)throws Exception{
  if(args.length!=4)throw new IllegalArgumentException("freshroot modernJava truejavac8 trueJava8");Path root=Paths.get(args[0]);Files.createDirectory(root);Path originals=root.resolve("original");Files.createDirectory(originals);Path source=originals.resolve("CompositionFlow.java");Files.writeString(source,SOURCE);Path selected=root.resolve("selected.txt");Files.writeString(selected,"CompositionFlow.java\n");Path converted=root.resolve("converted");CanonicalPatternPort.main(new String[]{originals.toString(),"",selected.toString(),converted.toString()});check(Files.readString(converted.resolve("owner-status.tsv")).equals("CompositionFlow.java\tSUPPORTED\t6\t0\n"),"Whole composition owner status");
  Path modern=root.resolve("modern"),release8=root.resolve("release8"),actual8=root.resolve("actual8");compile(source,modern,"17");compile(converted.resolve("post/CompositionFlow.java"),release8,"8");Files.createDirectory(actual8);run(args[2],List.of("-source","8","-target","8","-d",actual8.toString(),converted.resolve("post/CompositionFlow.java").toString()));String expected="imagenonenoneimageimagenone:4:1\n";check(run(args[1],List.of("-cp",modern.toString(),"CompositionFlow")).equals(expected),"Originallazyreadorder");check(run(args[3],List.of("-cp",release8.toString(),"CompositionFlow")).equals(expected),"Release8");check(run(args[3],List.of("-cp",actual8.toString(),"CompositionFlow")).equals(expected),"True8");
  Path other=root.resolve("other");Files.createDirectory(other);Files.writeString(other.resolve("Other.java"),"class Other { boolean good(Object value){if(value instanceof String text)return text.length()>0;return false;} }");Files.writeString(other.resolve("Nested.java"),"class Nested { boolean bad(Object value){return (value instanceof String text ? text : value) instanceof String again;} }");Path requests=root.resolve("other-selected.txt");Files.writeString(requests,"Other.java\nNested.java\n");Path out=root.resolve("other-output");CanonicalPatternPort.main(new String[]{other.toString(),"",requests.toString(),out.toString()});String status=Files.readString(out.resolve("owner-status.tsv"));check(status.contains("Other.java\tSUPPORTED\t1\t0")&&status.contains("Nested.java\tREJECTED\t2\t"),"Unsupported owner failclosed does not abort peer");check(!Files.exists(out.resolve("post/Nested.java")),"No partial rejected nested owner");System.out.println("PASS exact symbolic peer-binding composition original17=release8=true8");
 }
}
