# Mainstream stock Forge tuple. The game and FG3 tooling use Java 8.
java_version=8
minecraft_version=1.12.2
minecraft_version_range=[1.12.2]
mcp_version=1.12.2
forge_version=1.12.2-14.23.5.2864
forge_loader_version_range=[14.23.5.2864]
jei_version=4.16.1.1013
