# Actual stock Forge tuple. Player runtime Java17; FG3 tooling uses genuine Java8 remotely.
java_version=17
minecraft_version=1.12.2
minecraft_version_range=[1.12.2]
mcp_version=1.12.2
forge_version=1.12.2-14.23.5.2864
forge_loader_version_range=[14.23.5.2864]
jei_version=4.16.1.1013
