# Source-first Java21 candidate; reuses the native 1.20.6 family.
java_version=21
minecraft_version=1.20.5
minecraft_version_range=[1.20.5]
neo_form_version=1.20.5-20240423.152201
fabric_version=0.97.8+1.20.5
fabric_loader_version=0.18.2
neoforge_version=20.5.21-beta
neoforge_loader_version_range=[3,)
jei_version=18.0.0.66
rei_version=15.0.775
architectury_version=12.1.4
fabric_command_api_version=2.2.24+80f8cf510d
fabric_resource_loader_version=1.0.5+c5f2432c0d
fabric_networking_api_version=4.0.8+bd46f3a00d
fabric_lifecycle_events_version=2.3.4+c5fc38b30d
fabric_key_mapping_api_version=1.0.45+80f8cf510d
fabric_rendering_version=4.2.4+b21c00cb0d
