# Static compile candidate; primitive native input callback family.
java_version=21
minecraft_version=1.21.8
minecraft_version_range=[1.21.8]
neo_form_version=1.21.8-20250717.133445
fabric_version=0.136.1+1.21.8
fabric_loader_version=0.18.2
neoforge_version=21.8.54
neoforge_loader_version_range=[9,)
jei_version=24.2.0.6
rei_version=20.0.811
architectury_version=17.0.8
fabric_command_api_version=2.3.1+52fff9ec2c
fabric_resource_loader_version=3.1.12+020423442c
fabric_networking_api_version=5.1.0+57cb96dd2c
fabric_message_api_version=6.1.2+946bf4c32c
fabric_lifecycle_events_version=2.6.4+db4dfd852c
fabric_key_mapping_api_version=1.0.65+946bf4c32c
fabric_rendering_version=12.6.0+486b7ff72c
